### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by Kortenbach** [DaRubyMiner360/ParaCode#1]
Hi,

I came across this repository when looking for information on Paracode 
(programming language by former APV company).
I'm guessing this is the same programming language(?)
Perhaps you can tell a bit more about the history of Paracode in Readme.md?

I read that in the original Paracode language there was some kind of concurrency available?
Maybe you can tell a bit about that?

**Comment by DevReaper0** [comment]
Hello,

Apologies for the late reply as well as the confusion. This ParaCode is a different programming language than the company's. I actually wasn't even aware there *was* another language with the same name.

**Comment by Kortenbach** [comment]
Thank you for your reply! That's valuable information. Maybe you can add
this to the readme...

Best regards,

Bert

Op di 8 nov. 2022 22:20 schreef Robert Soncrant ***@***.***>:
